"""Localized interface and the first complete Python learning path."""

LANGUAGES = {
    "hy": "Հայերեն",
    "fr": "Français",
    "es": "Español",
    "en": "English",
    "ru": "Русский",
}

UI = {
    "en": {
        "next_chapter": "YOUR NEXT CHAPTER", "hero_card_cs": "CS foundations", "hero_card_python": "Build with Python",
        "nav_home": "Home", "nav_courses": "Learning paths", "nav_dashboard": "My progress",
        "nav_login": "Sign in", "nav_signup": "Start free", "nav_logout": "Sign out",
        "eyebrow": "A new orbit for your curiosity", "hero_title": "Learn to build what comes next.",
        "hero_copy": "Computer science, programming, and engineering, taught through clear lessons and hands-on challenges.",
        "hero_cta": "Start your 20-minute trial", "hero_secondary": "Explore the learning paths",
        "orbit_label": "YOUR NEXT IDEA", "orbit_value": "starts here",
        "what_title": "A universe of skills. One clear path.",
        "what_copy": "Build foundations in computer science, then turn ideas into working software.",
        "feature_cs": "Computer Science", "feature_cs_copy": "Algorithms, data structures, networks, operating systems, and the ideas behind every program.",
        "feature_code": "Languages that build", "feature_code_copy": "Python first, then JavaScript, HTML, CSS, SQL, C++, C#, Java, and Rust.",
        "feature_engineering": "Engineering in practice", "feature_engineering_copy": "Frontend, backend, testing, automation, AI, and the habits that make software reliable.",
        "paths_title": "Choose your first constellation", "python_title": "Python, from first line to advanced",
        "python_copy": "Ten guided lessons: syntax, data, functions, object-oriented programming, algorithms, testing, and async.",
        "cs_title": "Computer Science", "cs_copy": "The concepts that make every language easier to understand.",
        "soon": "Next in the roadmap", "trial_label": "Your free access", "trial_remaining": "Time left",
        "trial_minutes": "Your 20-minute trial began when you created your account.",
        "subscribe": "Unlock Python · $25 once", "trial_ended": "Your trial has ended",
        "locked_copy": "Get lifetime access to the complete Python course for one $25 payment.", "billing_setup": "One-time course payment is ready to connect. The owner needs to add the Stripe key and Python price ID.",
        "price": "$25 · one-time", "create_account": "Create your account", "sign_in_title": "Welcome back",
        "email": "Email", "password": "Password", "password_hint": "At least 8 characters",
        "register": "Create account and start trial", "login": "Sign in", "have_account": "Already have an account?",
        "need_account": "New to Lumincode?", "error_email": "Enter a valid email address.",
        "error_password": "Use a password with at least 8 characters.",
        "error_exists": "An account with this email already exists.", "error_login": "Email or password is incorrect.",
        "dashboard_title": "Your learning orbit", "welcome": "Welcome back",
        "points": "points", "level": "Level", "completed": "completed", "continue_python": "Continue Python",
        "python_path": "Python learning path", "lesson_count": "10 lessons · beginner to advanced",
        "lesson": "Lesson", "theory": "Theory", "code": "Code lab", "algorithm": "How it works",
        "hint": "Hint", "video": "Video", "quiz": "Quick check", "video_placeholder": "Video lesson slot",
        "video_copy": "A short video can be added here. The lesson and code examples work without it.",
        "question": "Choose one answer", "submit_answer": "Check answer", "correct": "Correct — +100 points for this lesson.",
        "incorrect": "Not quite. Review the explanation and try again.", "already_complete": "Lesson already complete; another correct answer will not add duplicate points.",
        "lesson_done": "Complete", "lesson_locked": "Locked", "lesson_open": "Open lesson",
        "back_course": "All Python lessons", "level_next": "points to your next level",
        "language": "Language", "footer_note": "Built for curious minds, one idea at a time.",
        "contact_placeholder": "Contact email will be added by the founder.",
        "trial_expired_tag": "Trial ended", "trial_active_tag": "Trial active",
        "access_note": "After the 20-minute trial, buy each complete course once for $25.",
        "csrf_error": "This form expired. Reload the page and try again.",
        "not_found": "This lesson could not be found.", "billing_error": "Payments are not configured yet.",
    },
    "ru": {
        "next_chapter": "ТВОЯ СЛЕДУЮЩАЯ ГЛАВА", "hero_card_cs": "Основы Computer Science", "hero_card_python": "Создавай на Python",
        "nav_home": "Главная", "nav_courses": "Направления", "nav_dashboard": "Мой прогресс",
        "nav_login": "Войти", "nav_signup": "Начать бесплатно", "nav_logout": "Выйти",
        "eyebrow": "Новая орбита для любознательных", "hero_title": "Учись создавать технологии будущего.",
        "hero_copy": "Computer Science, программирование и инженерия — через понятные уроки и практические задачи.",
        "hero_cta": "Начать пробный доступ на 20 минут", "hero_secondary": "Посмотреть направления",
        "orbit_label": "ТВОЯ СЛЕДУЮЩАЯ ИДЕЯ", "orbit_value": "начинается здесь",
        "what_title": "Вселенная навыков. Один понятный путь.",
        "what_copy": "Освой основы Computer Science и научись превращать идеи в работающие программы.",
        "feature_cs": "Computer Science", "feature_cs_copy": "Алгоритмы, структуры данных, сети, операционные системы и идеи, лежащие в основе программ.",
        "feature_code": "Языки программирования", "feature_code_copy": "Сначала Python, затем JavaScript, HTML, CSS, SQL, C++, C#, Java и Rust.",
        "feature_engineering": "Инженерная практика", "feature_engineering_copy": "Фронтенд, бэкенд, тестирование, автоматизация, AI и надёжная разработка.",
        "paths_title": "Выбери первое созвездие", "python_title": "Python: от первой строки до продвинутого уровня",
        "python_copy": "Десять уроков: синтаксис, данные, функции, ООП, алгоритмы, тестирование и async.",
        "cs_title": "Computer Science", "cs_copy": "Идеи, которые помогают понимать любой язык программирования.",
        "soon": "Следующий этап", "trial_label": "Бесплатный доступ", "trial_remaining": "Осталось",
        "trial_minutes": "20-минутный пробный доступ начался при создании аккаунта.",
        "subscribe": "Открыть курс Python · $25 один раз", "trial_ended": "Пробный доступ закончился",
        "locked_copy": "Полный курс Python с постоянным доступом стоит $25 один раз.", "billing_setup": "Осталось подключить Stripe и указать ID цены Python для разовой оплаты.",
        "price": "$25 · один платёж", "create_account": "Создать аккаунт", "sign_in_title": "С возвращением",
        "email": "Электронная почта", "password": "Пароль", "password_hint": "Не менее 8 символов",
        "register": "Создать аккаунт и начать пробный доступ", "login": "Войти", "have_account": "Уже есть аккаунт?",
        "need_account": "Впервые в Lumincode?", "error_email": "Введи корректный адрес электронной почты.",
        "error_password": "Пароль должен содержать не менее 8 символов.",
        "error_exists": "Аккаунт с таким адресом уже существует.", "error_login": "Неверная почта или пароль.",
        "dashboard_title": "Твоя учебная орбита", "welcome": "С возвращением",
        "points": "очков", "level": "Уровень", "completed": "пройдено", "continue_python": "Продолжить Python",
        "python_path": "Курс Python", "lesson_count": "10 уроков · от основ до продвинутых тем",
        "lesson": "Урок", "theory": "Теория", "code": "Практика", "algorithm": "Как это работает",
        "hint": "Подсказка", "video": "Видео", "quiz": "Тест", "video_placeholder": "Место для видеоурока",
        "video_copy": "Позже сюда можно добавить короткое видео. Урок и примеры кода доступны и без него.",
        "question": "Выбери один ответ", "submit_answer": "Проверить ответ", "correct": "Верно — +100 очков за этот урок.",
        "incorrect": "Пока неверно. Перечитай объяснение и попробуй ещё раз.", "already_complete": "Урок уже пройден; повторный ответ не начислит очки второй раз.",
        "lesson_done": "Пройдено", "lesson_locked": "Закрыто", "lesson_open": "Открыть урок",
        "back_course": "Все уроки Python", "level_next": "очков до следующего уровня",
        "language": "Язык", "footer_note": "Для тех, кому интересно, как всё устроено.",
        "contact_placeholder": "Основатель добавит контактную почту позже.",
        "trial_expired_tag": "Пробный доступ завершён", "trial_active_tag": "Пробный доступ активен",
        "access_note": "После пробных 20 минут каждый полный курс можно купить отдельно за $25.",
        "csrf_error": "Форма устарела. Обнови страницу и попробуй ещё раз.",
        "not_found": "Урок не найден.", "billing_error": "Приём платежей пока не настроен.",
    },
    "fr": {
        "next_chapter": "LA SUITE DE VOTRE PARCOURS", "hero_card_cs": "Bases de l’informatique", "hero_card_python": "Créer avec Python",
        "nav_home": "Accueil", "nav_courses": "Parcours", "nav_dashboard": "Ma progression",
        "nav_login": "Connexion", "nav_signup": "Essai gratuit", "nav_logout": "Déconnexion",
        "eyebrow": "Une nouvelle orbite pour votre curiosité", "hero_title": "Apprenez à créer le futur.",
        "hero_copy": "Informatique, programmation et ingénierie, avec des leçons claires et des défis pratiques.",
        "hero_cta": "Démarrer l’essai de 20 minutes", "hero_secondary": "Découvrir les parcours",
        "orbit_label": "VOTRE PROCHAINE IDÉE", "orbit_value": "commence ici",
        "what_title": "Un univers de compétences. Un chemin clair.",
        "what_copy": "Apprenez les bases de l’informatique, puis transformez vos idées en logiciels.",
        "feature_cs": "Informatique", "feature_cs_copy": "Algorithmes, structures de données, réseaux, systèmes et principes fondamentaux.",
        "feature_code": "Langages de programmation", "feature_code_copy": "Python d’abord, puis JavaScript, HTML, CSS, SQL, C++, C#, Java et Rust.",
        "feature_engineering": "Ingénierie en pratique", "feature_engineering_copy": "Frontend, backend, tests, automatisation, IA et pratiques de qualité.",
        "paths_title": "Choisissez votre première constellation", "python_title": "Python, des bases aux sujets avancés",
        "python_copy": "Dix leçons guidées : syntaxe, données, fonctions, POO, algorithmes, tests et async.",
        "cs_title": "Informatique", "cs_copy": "Les concepts qui rendent chaque langage plus facile à comprendre.",
        "soon": "À venir", "trial_label": "Votre accès gratuit", "trial_remaining": "Temps restant",
        "trial_minutes": "Votre essai de 20 minutes a commencé lors de la création du compte.",
        "subscribe": "Débloquer Python · 25 $ une fois", "trial_ended": "Votre essai est terminé",
        "locked_copy": "Accès complet au cours Python pour un paiement unique de 25 $.", "billing_setup": "Il reste à connecter Stripe et l’identifiant du tarif Python à paiement unique.",
        "price": "25 $ · paiement unique", "create_account": "Créer un compte", "sign_in_title": "Bon retour",
        "email": "E-mail", "password": "Mot de passe", "password_hint": "8 caractères minimum",
        "register": "Créer un compte et démarrer l’essai", "login": "Se connecter", "have_account": "Vous avez déjà un compte ?",
        "need_account": "Nouveau sur Lumincode ?", "error_email": "Saisissez une adresse e-mail valide.",
        "error_password": "Le mot de passe doit contenir au moins 8 caractères.",
        "error_exists": "Un compte avec cet e-mail existe déjà.", "error_login": "E-mail ou mot de passe incorrect.",
        "dashboard_title": "Votre orbite d’apprentissage", "welcome": "Bon retour",
        "points": "points", "level": "Niveau", "completed": "terminé", "continue_python": "Continuer Python",
        "python_path": "Parcours Python", "lesson_count": "10 leçons · des bases à l’avancé",
        "lesson": "Leçon", "theory": "Théorie", "code": "Atelier de code", "algorithm": "Fonctionnement",
        "hint": "Indice", "video": "Vidéo", "quiz": "Quiz", "video_placeholder": "Emplacement vidéo",
        "video_copy": "Une courte vidéo pourra être ajoutée ici. La leçon fonctionne sans vidéo.",
        "question": "Choisissez une réponse", "submit_answer": "Vérifier", "correct": "Correct — +100 points pour cette leçon.",
        "incorrect": "Pas tout à fait. Relisez l’explication et réessayez.", "already_complete": "Leçon déjà terminée ; les points ne seront pas attribués deux fois.",
        "lesson_done": "Terminé", "lesson_locked": "Verrouillé", "lesson_open": "Ouvrir la leçon",
        "back_course": "Toutes les leçons Python", "level_next": "points avant le niveau suivant",
        "language": "Langue", "footer_note": "Pour les esprits curieux, une idée à la fois.",
        "contact_placeholder": "L’adresse de contact sera ajoutée par le fondateur.",
        "trial_expired_tag": "Essai terminé", "trial_active_tag": "Essai actif",
        "access_note": "Après l’essai de 20 minutes, chaque cours complet s’achète séparément pour 25 $.",
        "csrf_error": "Ce formulaire a expiré. Rechargez la page et réessayez.",
        "not_found": "Cette leçon est introuvable.", "billing_error": "Les paiements ne sont pas encore configurés.",
    },
    "es": {
        "next_chapter": "TU PRÓXIMO CAPÍTULO", "hero_card_cs": "Fundamentos de CS", "hero_card_python": "Crea con Python",
        "nav_home": "Inicio", "nav_courses": "Rutas de aprendizaje", "nav_dashboard": "Mi progreso",
        "nav_login": "Iniciar sesión", "nav_signup": "Prueba gratis", "nav_logout": "Salir",
        "eyebrow": "Una nueva órbita para tu curiosidad", "hero_title": "Aprende a crear lo que viene.",
        "hero_copy": "Ciencias de la computación, programación e ingeniería con lecciones claras y retos prácticos.",
        "hero_cta": "Iniciar prueba de 20 minutos", "hero_secondary": "Explorar las rutas",
        "orbit_label": "TU PRÓXIMA IDEA", "orbit_value": "empieza aquí",
        "what_title": "Un universo de habilidades. Un camino claro.",
        "what_copy": "Aprende fundamentos de computación y convierte ideas en software funcional.",
        "feature_cs": "Ciencias de la computación", "feature_cs_copy": "Algoritmos, estructuras de datos, redes, sistemas operativos y sus fundamentos.",
        "feature_code": "Lenguajes de programación", "feature_code_copy": "Primero Python; después JavaScript, HTML, CSS, SQL, C++, C#, Java y Rust.",
        "feature_engineering": "Ingeniería práctica", "feature_engineering_copy": "Frontend, backend, pruebas, automatización, IA y buenas prácticas.",
        "paths_title": "Elige tu primera constelación", "python_title": "Python, desde cero hasta avanzado",
        "python_copy": "Diez lecciones: sintaxis, datos, funciones, POO, algoritmos, pruebas y async.",
        "cs_title": "Ciencias de la computación", "cs_copy": "Conceptos que ayudan a entender cualquier lenguaje.",
        "soon": "Próximamente", "trial_label": "Tu acceso gratuito", "trial_remaining": "Tiempo restante",
        "trial_minutes": "La prueba de 20 minutos empezó al crear tu cuenta.",
        "subscribe": "Desbloquear Python · $25 una vez", "trial_ended": "La prueba ha terminado",
        "locked_copy": "Acceso completo al curso de Python por un pago único de $25.", "billing_setup": "Falta conectar Stripe y el ID del precio único de Python.",
        "price": "$25 · pago único", "create_account": "Crear cuenta", "sign_in_title": "Qué bueno verte",
        "email": "Correo electrónico", "password": "Contraseña", "password_hint": "Al menos 8 caracteres",
        "register": "Crear cuenta e iniciar prueba", "login": "Iniciar sesión", "have_account": "¿Ya tienes una cuenta?",
        "need_account": "¿Nuevo en Lumincode?", "error_email": "Escribe un correo electrónico válido.",
        "error_password": "La contraseña debe tener al menos 8 caracteres.",
        "error_exists": "Ya existe una cuenta con ese correo.", "error_login": "El correo o la contraseña no son correctos.",
        "dashboard_title": "Tu órbita de aprendizaje", "welcome": "Qué bueno verte",
        "points": "puntos", "level": "Nivel", "completed": "completado", "continue_python": "Continuar Python",
        "python_path": "Ruta de Python", "lesson_count": "10 lecciones · de principiante a avanzado",
        "lesson": "Lección", "theory": "Teoría", "code": "Laboratorio", "algorithm": "Cómo funciona",
        "hint": "Pista", "video": "Vídeo", "quiz": "Prueba rápida", "video_placeholder": "Espacio para el vídeo",
        "video_copy": "Aquí se podrá añadir un vídeo breve. La lección también funciona sin él.",
        "question": "Elige una respuesta", "submit_answer": "Comprobar respuesta", "correct": "Correcto — +100 puntos por esta lección.",
        "incorrect": "Casi. Repasa la explicación e inténtalo de nuevo.", "already_complete": "Lección completada; no se duplican los puntos.",
        "lesson_done": "Completado", "lesson_locked": "Bloqueado", "lesson_open": "Abrir lección",
        "back_course": "Todas las lecciones de Python", "level_next": "puntos para el siguiente nivel",
        "language": "Idioma", "footer_note": "Para mentes curiosas, una idea a la vez.",
        "contact_placeholder": "El fundador añadirá el correo de contacto más adelante.",
        "trial_expired_tag": "Prueba terminada", "trial_active_tag": "Prueba activa",
        "access_note": "Tras los 20 minutos de prueba, cada curso completo se compra por separado por $25.",
        "csrf_error": "El formulario ha caducado. Recarga la página e inténtalo de nuevo.",
        "not_found": "No se encontró esta lección.", "billing_error": "Los pagos aún no están configurados.",
    },
    "hy": {
        "next_chapter": "ՔՈ ՀԱՋՈՐԴ ԳԼՈՒԽԸ", "hero_card_cs": "Computer Science-ի հիմքերը", "hero_card_python": "Ստեղծիր Python-ով",
        "nav_home": "Գլխավոր", "nav_courses": "Ուսումնական ուղիներ", "nav_dashboard": "Իմ առաջընթացը",
        "nav_login": "Մուտք", "nav_signup": "Անվճար փորձաշրջան", "nav_logout": "Ելք",
        "eyebrow": "Քո հետաքրքրասիրության նոր ուղեծիրը", "hero_title": "Սովորիր ստեղծել ապագայի տեխնոլոգիաները։",
        "hero_copy": "Համակարգչային գիտություն, ծրագրավորում և ինժեներիա՝ պարզ դասերով ու գործնական առաջադրանքներով։",
        "hero_cta": "Սկսել 20 րոպեանոց փորձաշրջանը", "hero_secondary": "Դիտել ուսումնական ուղիները",
        "orbit_label": "ՔՈ ՀԱՋՈՐԴ ԳԱՂԱՓԱՐԸ", "orbit_value": "սկսվում է այստեղ",
        "what_title": "Հմտությունների տիեզերք։ Մեկ հստակ ուղի։",
        "what_copy": "Սովորիր համակարգչային գիտության հիմքերը և գաղափարները վերածիր աշխատող ծրագրերի։",
        "feature_cs": "Համակարգչային գիտություն", "feature_cs_copy": "Ալգորիթմներ, տվյալների կառուցվածքներ, ցանցեր, օպերացիոն համակարգեր և ծրագրերի հիմքերը։",
        "feature_code": "Ծրագրավորման լեզուներ", "feature_code_copy": "Սկսիր Python-ից, հետո անցիր JavaScript, HTML, CSS, SQL, C++, C#, Java և Rust լեզուներին։",
        "feature_engineering": "Ինժեներական գործելակերպ", "feature_engineering_copy": "Frontend, backend, թեստավորում, ավտոմատացում, AI և հուսալի ծրագրավորում։",
        "paths_title": "Ընտրիր առաջին համաստեղությունը", "python_title": "Python՝ առաջին տողից մինչև առաջադեմ թեմաներ",
        "python_copy": "Տասը դաս՝ շարահյուսություն, տվյալներ, ֆունկցիաներ, ՕՕԾ, ալգորիթմներ, թեստավորում և async։",
        "cs_title": "Համակարգչային գիտություն", "cs_copy": "Գաղափարներ, որոնք օգնում են հասկանալ ցանկացած ծրագրավորման լեզու։",
        "soon": "Հաջորդը ճանապարհային քարտեզում", "trial_label": "Անվճար հասանելիություն", "trial_remaining": "Մնացել է",
        "trial_minutes": "20 րոպեանոց փորձաշրջանը սկսվել է հաշիվ ստեղծելիս։",
        "subscribe": "Բացել Python-ը · $25՝ մեկ անգամ", "trial_ended": "Փորձաշրջանն ավարտվել է",
        "locked_copy": "Python-ի ամբողջական դասընթացի մշտական հասանելիությունն արժե $25՝ մեկանգամյա վճարմամբ։", "billing_setup": "Մնում է միացնել Stripe-ը և նշել Python-ի մեկանգամյա գնի ID-ն։",
        "price": "$25 · մեկանգամյա", "create_account": "Ստեղծել հաշիվ", "sign_in_title": "Բարի վերադարձ",
        "email": "Էլեկտրոնային փոստ", "password": "Գաղտնաբառ", "password_hint": "Առնվազն 8 նիշ",
        "register": "Ստեղծել հաշիվ և սկսել փորձաշրջանը", "login": "Մուտք գործել", "have_account": "Արդեն հաշիվ ունե՞ս։",
        "need_account": "Նոր ե՞ս Lumincode-ում։", "error_email": "Մուտքագրիր վավեր էլեկտրոնային հասցե։",
        "error_password": "Գաղտնաբառը պետք է ունենա առնվազն 8 նիշ։",
        "error_exists": "Այս հասցեով հաշիվ արդեն կա։", "error_login": "Էլեկտրոնային հասցեն կամ գաղտնաբառը սխալ է։",
        "dashboard_title": "Քո ուսումնական ուղեծիրը", "welcome": "Բարի վերադարձ",
        "points": "միավոր", "level": "Մակարդակ", "completed": "ավարտված", "continue_python": "Շարունակել Python-ը",
        "python_path": "Python-ի ուսումնական ուղի", "lesson_count": "10 դաս · հիմունքներից մինչև առաջադեմ",
        "lesson": "Դաս", "theory": "Տեսություն", "code": "Կոդի լաբորատորիա", "algorithm": "Ինչպես է աշխատում",
        "hint": "Հուշում", "video": "Տեսանյութ", "quiz": "Արագ թեստ", "video_placeholder": "Տեսադասի տեղ",
        "video_copy": "Այստեղ հետո կարելի է ավելացնել կարճ տեսանյութ։ Դասն ու կոդի օրինակները գործում են նաև առանց դրա։",
        "question": "Ընտրիր մեկ պատասխան", "submit_answer": "Ստուգել պատասխանը", "correct": "Ճիշտ է — այս դասի համար +100 միավոր։",
        "incorrect": "Դեռ ոչ։ Կարդա բացատրությունը և փորձիր կրկին։", "already_complete": "Դասն արդեն ավարտված է․ միավորները երկրորդ անգամ չեն ավելանա։",
        "lesson_done": "Ավարտված է", "lesson_locked": "Փակ է", "lesson_open": "Բացել դասը",
        "back_course": "Python-ի բոլոր դասերը", "level_next": "միավոր մինչև հաջորդ մակարդակ",
        "language": "Լեզու", "footer_note": "Հետաքրքրասեր մտքերի համար՝ գաղափար առ գաղափար։",
        "contact_placeholder": "Հիմնադիրը կապի էլեկտրոնային հասցեն կավելացնի ավելի ուշ։",
        "trial_expired_tag": "Փորձաշրջանն ավարտվել է", "trial_active_tag": "Փորձաշրջանն ակտիվ է",
        "access_note": "20 րոպեից հետո յուրաքանչյուր ամբողջական դասընթաց գնվում է առանձին՝ $25 մեկանգամյա վճարմամբ։",
        "csrf_error": "Այս ձևն այլևս ակտիվ չէ։ Թարմացրու էջը և փորձիր կրկին։",
        "not_found": "Այս դասը չի գտնվել։", "billing_error": "Վճարումները դեռ կարգավորված չեն։",
    },
}

UI_EXTRA = {
    "en": {
        "map_section": "01 / THE MAP", "paths_section": "02 / THE LEARNING PATHS", "trial_section": "03 / BEGIN WITH CURIOSITY",
        "first_track": "01 / FIRST TRACK", "foundation": "02 / THE FOUNDATION", "dashboard_space": "YOUR SPACE / 01",
        "current_path": "YOUR CURRENT PATH", "curriculum": "THE CURRICULUM", "concept_label": "CONCEPT / 01",
        "code_lab_label": "CODE LAB / 02", "system_label": "UNDER THE HOOD / 03", "navigation_label": "NAVIGATION / 04",
        "watch_label": "WATCH / 05", "checkpoint_label": "CHECKPOINT / 06", "account_access": "ACCOUNT ACCESS",
        "your_orbit": "YOUR ORBIT", "all_paths": "ALL LEARNING PATHS", "copy_code": "Copy code", "copied": "Copied",
        "account_note": "Your password is stored as a one-way hash. Email confirmation will be added after an email provider is chosen.",
        "benefit_python": "Python from beginner to advanced", "benefit_cs": "Computer Science foundations",
        "benefit_progress": "Save your progress and earn points", "benefit_tracks": "New languages and engineering tracks",
        "subscribed": "Subscription active", "video_slot": "VIDEO SLOT",
        "courses_title": "Choose a discipline. Build the full skill.", "courses_copy": "Each complete course is $25 once. Start with the finished Python path; the rest are being built with the same depth.", "unlock_course": "Unlock the complete Python course",
        "course_price": "$25 · once", "course_ready": "AVAILABLE NOW", "course_soon": "IN THE ROADMAP", "owner_access": "Founder access · all available courses unlocked",
        "track_cs_copy": "Algorithms, data structures, networks, operating systems, and the ideas behind every program.",
        "track_language_copy": "Learn syntax through projects, debugging, tests, and production-ready habits.", "track_engineering_copy": "Turn concepts into reliable systems with design practice, tools, and real build challenges.",
        "benefit_challenges": "Two knowledge checks in every lesson", "benefit_projects": "Build missions, video lessons, and saved progress",
        "challenge_label": "BUILD CHALLENGE", "professional_label": "ENGINEERING PRACTICE", "checkpoint_two": "TRACE THE CODE", "challenge_quality": "Before you call it done: test a normal input, a boundary case, and a failure case.",
        "trace_prompt": "Predict what this program does, then choose the result.", "display_name": "Your name (optional)",
    },
    "ru": {
        "map_section": "01 / КАРТА НАВЫКОВ", "paths_section": "02 / УЧЕБНЫЕ НАПРАВЛЕНИЯ", "trial_section": "03 / НАЧНИ С ИНТЕРЕСА",
        "first_track": "01 / ПЕРВЫЙ КУРС", "foundation": "02 / ОСНОВА", "dashboard_space": "ТВОЯ ОРБИТА / 01",
        "current_path": "ТЕКУЩЕЕ НАПРАВЛЕНИЕ", "curriculum": "ПЛАН ОБУЧЕНИЯ", "concept_label": "ТЕОРИЯ / 01",
        "code_lab_label": "ПРАКТИКА / 02", "system_label": "ПОД КАПОТОМ / 03", "navigation_label": "НАВИГАЦИЯ / 04",
        "watch_label": "СМОТРИ / 05", "checkpoint_label": "ПРОВЕРКА / 06", "account_access": "ДОСТУП К АККАУНТУ",
        "your_orbit": "ТВОЯ ОРБИТА", "all_paths": "ВСЕ УЧЕБНЫЕ НАПРАВЛЕНИЯ", "copy_code": "Копировать код", "copied": "Скопировано",
        "account_note": "Пароль хранится в виде необратимого хеша. Подтверждение почты добавим после выбора почтового сервиса.",
        "benefit_python": "Python от основ до продвинутых тем", "benefit_cs": "Основы Computer Science",
        "benefit_progress": "Сохраняй прогресс и зарабатывай очки", "benefit_tracks": "Новые языки и инженерные курсы",
        "subscribed": "Подписка активна", "video_slot": "МЕСТО ДЛЯ ВИДЕО",
        "courses_title": "Выбери направление. Освой его целиком.", "courses_copy": "Полный курс стоит $25 один раз. Начни с готового Python; остальные направления создаются с такой же глубиной.", "unlock_course": "Открой полный курс Python",
        "course_price": "$25 · один раз", "course_ready": "УЖЕ ДОСТУПЕН", "course_soon": "В ПЛАНЕ", "owner_access": "Доступ основателя · все готовые курсы открыты",
        "track_cs_copy": "Алгоритмы, структуры данных, сети, операционные системы и принципы программ.",
        "track_language_copy": "От синтаксиса к проектам, отладке, тестам и профессиональным привычкам.", "track_engineering_copy": "Превращай идеи в надёжные системы через проектирование, инструменты и практику.",
        "benefit_challenges": "Две проверки знаний в каждом уроке", "benefit_projects": "Практические проекты, видео и сохранение прогресса",
        "challenge_label": "ПРАКТИЧЕСКИЙ ПРОЕКТ", "professional_label": "ИНЖЕНЕРНАЯ ПРАКТИКА", "checkpoint_two": "РАЗБЕРИ КОД", "challenge_quality": "Перед завершением проверь обычный ввод, граничный случай и ошибку.",
        "trace_prompt": "Предскажи, что делает программа, затем выбери результат.", "display_name": "Имя (необязательно)",
    },
    "fr": {
        "map_section": "01 / LA CARTE", "paths_section": "02 / LES PARCOURS", "trial_section": "03 / COMMENCER PAR CURIOSITÉ",
        "first_track": "01 / PREMIER PARCOURS", "foundation": "02 / LES FONDATIONS", "dashboard_space": "VOTRE ESPACE / 01",
        "current_path": "VOTRE PARCOURS ACTUEL", "curriculum": "LE PROGRAMME", "concept_label": "CONCEPT / 01",
        "code_lab_label": "ATELIER CODE / 02", "system_label": "SOUS LE CAPOT / 03", "navigation_label": "NAVIGATION / 04",
        "watch_label": "REGARDER / 05", "checkpoint_label": "ÉTAPE CLÉ / 06", "account_access": "ACCÈS AU COMPTE",
        "your_orbit": "VOTRE ORBITE", "all_paths": "TOUS LES PARCOURS", "copy_code": "Copier le code", "copied": "Copié",
        "account_note": "Votre mot de passe est stocké sous forme de hachage irréversible. La confirmation par e-mail viendra après le choix d’un fournisseur.",
        "benefit_python": "Python, des bases aux sujets avancés", "benefit_cs": "Fondamentaux de l’informatique",
        "benefit_progress": "Enregistrer vos progrès et gagner des points", "benefit_tracks": "Nouveaux langages et parcours d’ingénierie",
        "subscribed": "Abonnement actif", "video_slot": "EMPLACEMENT VIDÉO",
        "courses_title": "Choisissez un domaine. Maîtrisez-le pleinement.", "courses_copy": "Chaque cours complet coûte 25 $ une seule fois. Commencez par Python, déjà disponible ; les autres parcours sont en préparation.", "unlock_course": "Débloquer le cours complet de Python",
        "course_price": "25 $ · une fois", "course_ready": "DISPONIBLE", "course_soon": "À VENIR", "owner_access": "Accès fondateur · tous les cours disponibles sont ouverts",
        "track_cs_copy": "Algorithmes, structures de données, réseaux, systèmes et principes de chaque programme.",
        "track_language_copy": "Apprenez la syntaxe par des projets, le débogage, les tests et des pratiques professionnelles.", "track_engineering_copy": "Transformez les concepts en systèmes fiables grâce à la conception et à la pratique.",
        "benefit_challenges": "Deux vérifications dans chaque leçon", "benefit_projects": "Défis pratiques, vidéos et progression enregistrée",
        "challenge_label": "DÉFI DE CONSTRUCTION", "professional_label": "PRATIQUE D’INGÉNIERIE", "checkpoint_two": "SUIVEZ LE CODE", "challenge_quality": "Avant de terminer : testez un cas normal, un cas limite et un échec.",
        "trace_prompt": "Prédisez ce que fait le programme, puis choisissez le résultat.", "display_name": "Votre nom (facultatif)",
    },
    "es": {
        "map_section": "01 / EL MAPA", "paths_section": "02 / LAS RUTAS", "trial_section": "03 / EMPIEZA CON CURIOSIDAD",
        "first_track": "01 / PRIMERA RUTA", "foundation": "02 / LOS FUNDAMENTOS", "dashboard_space": "TU ESPACIO / 01",
        "current_path": "TU RUTA ACTUAL", "curriculum": "EL TEMARIO", "concept_label": "CONCEPTO / 01",
        "code_lab_label": "LABORATORIO / 02", "system_label": "BAJO EL CAPÓ / 03", "navigation_label": "NAVEGACIÓN / 04",
        "watch_label": "VER / 05", "checkpoint_label": "PUNTO DE CONTROL / 06", "account_access": "ACCESO A LA CUENTA",
        "your_orbit": "TU ÓRBITA", "all_paths": "TODAS LAS RUTAS", "copy_code": "Copiar código", "copied": "Copiado",
        "account_note": "La contraseña se guarda como un hash irreversible. Añadiremos la confirmación por correo al elegir un proveedor.",
        "benefit_python": "Python desde cero hasta avanzado", "benefit_cs": "Fundamentos de computación",
        "benefit_progress": "Guarda tu progreso y gana puntos", "benefit_tracks": "Nuevos lenguajes y rutas de ingeniería",
        "subscribed": "Suscripción activa", "video_slot": "ESPACIO PARA VÍDEO",
        "courses_title": "Elige una disciplina. Domínala por completo.", "courses_copy": "Cada curso completo cuesta $25 una sola vez. Empieza con Python, que ya está listo; los demás están en desarrollo.", "unlock_course": "Desbloquear el curso completo de Python",
        "course_price": "$25 · una vez", "course_ready": "DISPONIBLE", "course_soon": "PRÓXIMAMENTE", "owner_access": "Acceso de fundador · todos los cursos disponibles están abiertos",
        "track_cs_copy": "Algoritmos, estructuras de datos, redes, sistemas operativos y fundamentos de cada programa.",
        "track_language_copy": "Aprende sintaxis con proyectos, depuración, pruebas y hábitos profesionales.", "track_engineering_copy": "Convierte ideas en sistemas fiables con diseño, herramientas y práctica real.",
        "benefit_challenges": "Dos preguntas de repaso en cada lección", "benefit_projects": "Retos prácticos, vídeos y progreso guardado",
        "challenge_label": "RETO DE CONSTRUCCIÓN", "professional_label": "PRÁCTICA DE INGENIERÍA", "checkpoint_two": "SIGUE EL CÓDIGO", "challenge_quality": "Antes de terminar: prueba una entrada normal, un caso límite y un error.",
        "trace_prompt": "Predice qué hace el programa y luego elige el resultado.", "display_name": "Tu nombre (opcional)",
    },
    "hy": {
        "map_section": "01 / ՀՄՏՈՒԹՅՈՒՆՆԵՐԻ ՔԱՐՏԵԶ", "paths_section": "02 / ՈՒՍՈՒՄՆԱԿԱՆ ՈՒՂԻՆԵՐ", "trial_section": "03 / ՍԿՍԻՐ ՀԵՏԱՔՐՔՐՈՒԹՅԱՄԲ",
        "first_track": "01 / ԱՌԱՋԻՆ ՈՒՂԻՆ", "foundation": "02 / ՀԻՄՔԵՐԸ", "dashboard_space": "ՔՈ ՏԱՐԱԾՔԸ / 01",
        "current_path": "ՔՈ ԸՆԹԱՑԻԿ ՈՒՂԻՆ", "curriculum": "ՈՒՍՈՒՄՆԱԿԱՆ ԾՐԱԳԻՐ", "concept_label": "ԳԱՂԱՓԱՐ / 01",
        "code_lab_label": "ԿՈԴԻ ԼԱԲՈՐԱՏՈՐԻԱ / 02", "system_label": "ՆԵՐՔԻՆ ԳՈՐԾԸՆԹԱՑ / 03", "navigation_label": "ՆԱՎԻԳԱՑԻԱ / 04",
        "watch_label": "ԴԻՏԻՐ / 05", "checkpoint_label": "ՍՏՈՒԳՄԱՆ ԿԵՏ / 06", "account_access": "ՀԱՇՎԻ ՄՈՒՏՔ",
        "your_orbit": "ՔՈ ՈՒՂԵԾԻՐԸ", "all_paths": "ԲՈԼՈՐ ՈՒՍՈՒՄՆԱԿԱՆ ՈՒՂԻՆԵՐԸ", "copy_code": "Պատճենել կոդը", "copied": "Պատճենված է",
        "account_note": "Գաղտնաբառը պահվում է միակողմանի հեշի տեսքով։ Էլ․ փոստի հաստատումը կավելացնենք փոստային ծառայություն ընտրելուց հետո։",
        "benefit_python": "Python՝ հիմունքներից մինչև առաջադեմ թեմաներ", "benefit_cs": "Համակարգչային գիտության հիմքերը",
        "benefit_progress": "Պահպանիր առաջընթացը և վաստակիր միավորներ", "benefit_tracks": "Նոր լեզուներ և ինժեներական ուղիներ",
        "subscribed": "Բաժանորդագրությունն ակտիվ է", "video_slot": "ՏԵՍԱՆՅՈՒԹԻ ՏԵՂ",
        "courses_title": "Ընտրիր ուղղությունդ ու զարգացրու ամբողջական հմտություն։", "courses_copy": "Յուրաքանչյուր ամբողջական դասընթացն արժե $25՝ մեկ անգամ։ Սկսիր պատրաստ Python դասընթացից․ մյուս ուղղությունները կառուցվում են նույն խորությամբ։", "unlock_course": "Բացել Python-ի ամբողջական դասընթացը",
        "course_price": "$25 · մեկ անգամ", "course_ready": "ՀԱՍԱՆԵԼԻ Է", "course_soon": "ՃԱՆԱՊԱՐՀԱՅԻՆ ՔԱՐՏԵԶՈՒՄ", "owner_access": "Հիմնադրի հասանելիություն · պատրաստ դասընթացներն ամբողջությամբ բաց են",
        "track_cs_copy": "Ալգորիթմներ, տվյալների կառուցվածքներ, ցանցեր, օպերացիոն համակարգեր և ծրագրերի հիմքում եղած գաղափարներ։",
        "track_language_copy": "Սովորիր շարահյուսությունը նախագծերով, վրիպազերծմամբ, թեստերով ու մասնագիտական սովորություններով։", "track_engineering_copy": "Գաղափարները վերածիր հուսալի համակարգերի՝ նախագծմամբ, գործիքներով և իրական պրակտիկայով։",
        "benefit_challenges": "Յուրաքանչյուր դասում երկու գիտելիքի ստուգում", "benefit_projects": "Գործնական նախագծեր, տեսանյութեր և պահվող առաջընթաց",
        "challenge_label": "ՍՏԵՂԾՄԱՆ ՆԱԽԱԳԻԾ", "professional_label": "ԻՆԺԵՆԵՐԱԿԱՆ ՊՐԱԿՏԻԿԱ", "checkpoint_two": "ՀԵՏԵՎԻՐ ԿՈԴԻՆ", "challenge_quality": "Ավարտելուց առաջ ստուգիր սովորական մուտքը, սահմանային դեպքն ու սխալի դեպքը։",
        "trace_prompt": "Կանխատեսիր ծրագրի աշխատանքը, հետո ընտրիր արդյունքը։", "display_name": "Անունդ (ըստ ցանկության)",
    },
}

# A second, lesson-specific trace question makes each checkpoint test both
# vocabulary and the learner's ability to reason about a small code example.
TRACE_CASES = {
    "first-program": {
        "code": 'age = int("21")\nprint(type(age).__name__)', "answer": 0,
        "options": {"en": ["int", "str", "float"], "ru": ["int", "str", "float"], "fr": ["int", "str", "float"], "es": ["int", "str", "float"], "hy": ["int", "str", "float"]},
        "mission": {"en": "Write a greet(name) function that prints a personal welcome, then try it with two different names.", "ru": "Напиши greet(name), которая приветствует человека по имени, и проверь её с двумя именами.", "fr": "Écrivez greet(name), qui salue une personne par son nom, puis testez-la avec deux noms.", "es": "Escribe greet(name), que salude a una persona por su nombre, y pruébala con dos nombres.", "hy": "Գրիր greet(name) ֆունկցիան, որը ողջունում է անունով, ապա փորձիր երկու տարբեր անուններով։"},
    },
    "values-and-types": {
        "code": 'is_ready = True\nprint(type(is_ready).__name__)', "answer": 0,
        "options": {"en": ["bool", "str", "int"], "ru": ["bool", "str", "int"], "fr": ["bool", "str", "int"], "es": ["bool", "str", "int"], "hy": ["bool", "str", "int"]},
        "mission": {"en": "Read a price as text, convert it to a number, and calculate a 10% discount without mixing text and arithmetic.", "ru": "Прочитай цену как текст, преобразуй её в число и вычисли скидку 10 %, не смешивая текст и вычисления.", "fr": "Lisez un prix sous forme de texte, convertissez-le en nombre et calculez une remise de 10 %.", "es": "Lee un precio como texto, conviértelo en número y calcula un descuento del 10 % sin mezclar tipos.", "hy": "Գինը կարդա որպես տեքստ, փոխարկիր թվի ու հաշվի՛ր 10% զեղչը՝ առանց տեսակները խառնելու։"},
    },
    "branches-and-loops": {
        "code": 'for number in range(1, 5):\n    if number % 2 == 0:\n        print(number)', "answer": 0,
        "options": {"en": ["2, 4", "1, 3", "1, 2, 3, 4"], "ru": ["2, 4", "1, 3", "1, 2, 3, 4"], "fr": ["2, 4", "1, 3", "1, 2, 3, 4"], "es": ["2, 4", "1, 3", "1, 2, 3, 4"], "hy": ["2, 4", "1, 3", "1, 2, 3, 4"]},
        "mission": {"en": "Build a small FizzBuzz from 1 to 30. Explain why each branch runs and include the boundary values 1 and 30.", "ru": "Сделай FizzBuzz от 1 до 30. Объясни ветви и проверь границы 1 и 30.", "fr": "Créez un petit FizzBuzz de 1 à 30. Expliquez chaque branche et vérifiez les bornes 1 et 30.", "es": "Crea un FizzBuzz del 1 al 30. Explica cada rama e incluye los límites 1 y 30.", "hy": "Ստեղծիր FizzBuzz՝ 1-ից 30։ Բացատրիր ճյուղերը և ստուգիր 1 ու 30 սահմանային արժեքները։"},
    },
    "collections": {
        "code": 'profile = {"name": "Mira", "level": 2}\nprint(profile["level"])', "answer": 0,
        "options": {"en": ["2", "Mira", "KeyError"], "ru": ["2", "Mira", "KeyError"], "fr": ["2", "Mira", "KeyError"], "es": ["2", "Mira", "KeyError"], "hy": ["2", "Mira", "KeyError"]},
        "mission": {"en": "Create a tiny contact book with a dictionary. Add, look up, update, and safely handle a missing name.", "ru": "Создай справочник на словаре. Добавь, найди и измени контакт, затем обработай отсутствующее имя.", "fr": "Créez un carnet de contacts avec un dictionnaire. Ajoutez, cherchez, modifiez et gérez un nom absent.", "es": "Crea una agenda con un diccionario. Añade, busca y actualiza contactos y gestiona un nombre inexistente.", "hy": "Ստեղծիր կոնտակտների փոքր բառարան։ Ավելացրու, գտիր, փոխիր կոնտակտը և ապահով մշակի բացակայող անունը։"},
    },
    "functions": {
        "code": 'def double(number):\n    return number * 2\n\nprint(double(4))', "answer": 0,
        "options": {"en": ["8", "4", "None"], "ru": ["8", "4", "None"], "fr": ["8", "4", "None"], "es": ["8", "4", "None"], "hy": ["8", "4", "None"]},
        "mission": {"en": "Write a shipping_cost(weight, express=False) function. Keep calculation separate from printing and test both delivery options.", "ru": "Напиши shipping_cost(weight, express=False). Отдели расчёт от вывода и проверь оба способа доставки.", "fr": "Écrivez shipping_cost(weight, express=False). Séparez le calcul de l’affichage et testez les deux options.", "es": "Escribe shipping_cost(weight, express=False). Separa el cálculo de la salida y prueba ambas opciones.", "hy": "Գրիր shipping_cost(weight, express=False) ֆունկցիան։ Հաշվարկը տարանջատիր արտածումից և փորձիր երկու տարբերակները։"},
    },
    "modules-errors-files": {
        "code": 'from pathlib import Path\nprint(Path("notes.txt").suffix)', "answer": 0,
        "options": {"en": [".txt", "notes", "None"], "ru": [".txt", "notes", "None"], "fr": [".txt", "notes", "None"], "es": [".txt", "notes", "None"], "hy": [".txt", "notes", "None"]},
        "mission": {"en": "Save a note with pathlib and a with block. Handle a realistic file error without hiding unrelated failures.", "ru": "Сохрани заметку через pathlib и with. Обработай реальную ошибку файла, не скрывая остальные сбои.", "fr": "Enregistrez une note avec pathlib et with. Gérez une erreur de fichier sans masquer les autres problèmes.", "es": "Guarda una nota con pathlib y with. Gestiona un error de archivo sin ocultar otros fallos.", "hy": "Պահիր նշումը pathlib-ով և with բլոկով։ Մշակիր ֆայլի հնարավոր սխալը՝ մյուս խափանումները չթաքցնելով։"},
    },
    "object-oriented-python": {
        "code": 'counter = Counter()\ncounter.increment()\nprint(counter.value)', "answer": 0,
        "options": {"en": ["1", "0", "AttributeError"], "ru": ["1", "0", "AttributeError"], "fr": ["1", "0", "AttributeError"], "es": ["1", "0", "AttributeError"], "hy": ["1", "0", "AttributeError"]},
        "mission": {"en": "Give Counter a reset method. Keep each counter's state independent and test two separate instances.", "ru": "Добавь Counter метод reset. Сохрани независимое состояние счётчиков и проверь два экземпляра.", "fr": "Ajoutez reset à Counter. Gardez l’état de chaque compteur indépendant et testez deux instances.", "es": "Añade reset a Counter. Mantén independiente el estado de cada contador y prueba dos instancias.", "hy": "Counter դասին ավելացրու reset մեթոդը։ Պահպանիր հաշվիչների անկախ վիճակը և փորձիր երկու օրինակ։"},
    },
    "algorithms-complexity": {
        "code": 'values = [2, 4, 8, 16]\n# Binary search discards half at each comparison', "answer": 0,
        "options": {"en": ["The input is sorted", "The input has no duplicates", "The list length is even"], "ru": ["Данные отсортированы", "Нет повторов", "Длина чётная"], "fr": ["Les données sont triées", "Aucun doublon", "La longueur est paire"], "es": ["Los datos están ordenados", "No hay duplicados", "La longitud es par"], "hy": ["Տվյալները դասավորված են", "Կրկնվող արժեքներ չկան", "Ցուցակի երկարությունը զույգ է"]},
        "mission": {"en": "Compare linear search and binary search on a sorted list. Count comparisons for several input sizes and describe the growth.", "ru": "Сравни линейный и бинарный поиск на отсортированном списке. Посчитай сравнения при разном размере и опиши рост.", "fr": "Comparez la recherche linéaire et binaire. Comptez les comparaisons selon la taille et décrivez leur croissance.", "es": "Compara la búsqueda lineal y binaria. Cuenta comparaciones con varios tamaños y explica su crecimiento.", "hy": "Համեմատիր գծային և երկուական որոնումները։ Տարբեր չափերի համար հաշվիր համեմատությունները և բացատրիր աճը։"},
    },
    "iterators-generators": {
        "code": 'def countdown(start):\n    while start > 0:\n        yield start\n        start -= 1\n\nprint(next(countdown(3)))', "answer": 0,
        "options": {"en": ["3", "2", "0"], "ru": ["3", "2", "0"], "fr": ["3", "2", "0"], "es": ["3", "2", "0"], "hy": ["3", "2", "0"]},
        "mission": {"en": "Write a generator that reads values one at a time and skips invalid entries. Show why it uses less memory than building a second list.", "ru": "Напиши генератор, который читает значения по одному и пропускает неверные. Объясни, почему это экономит память.", "fr": "Écrivez un générateur qui lit les valeurs une à une et ignore les invalides. Expliquez l’économie de mémoire.", "es": "Escribe un generador que lea valores uno a uno y omita los inválidos. Explica cómo ahorra memoria.", "hy": "Գրիր գեներատոր, որը արժեքները մշակում է հերթով ու բաց է թողնում սխալները։ Բացատրիր՝ ինչպես է այն խնայում հիշողությունը։"},
    },
    "testing-async": {
        "code": 'assert 2 + 2 == 4\nprint("test passed")', "answer": 0,
        "options": {"en": ["The assertion passes", "The assertion fails", "It returns 4"], "ru": ["Проверка пройдена", "Проверка не пройдена", "Возвращается 4"], "fr": ["La vérification réussit", "La vérification échoue", "Elle renvoie 4"], "es": ["La comprobación pasa", "La comprobación falla", "Devuelve 4"], "hy": ["Ստուգումն անցնում է", "Ստուգումը ձախողվում է", "Այն վերադարձնում է 4"]},
        "mission": {"en": "Test one success and one failure for a small async function. Replace the network call with a fake so the test stays fast and repeatable.", "ru": "Проверь успех и ошибку небольшой async-функции. Замени сеть заглушкой, чтобы тест был быстрым и повторяемым.", "fr": "Testez une réussite et un échec d’une fonction async. Remplacez le réseau par un faux service pour garder un test rapide et stable.", "es": "Prueba el éxito y el error de una función async. Sustituye la red por una simulación para que la prueba sea rápida y repetible.", "hy": "Փորձարկիր async ֆունկցիայի հաջողությունն ու սխալը։ Ցանցը փոխարինիր կեղծմամբ, որպեսզի թեստը լինի արագ ու կրկնելի։"},
    },
}

UI_LESSON_FLOW = {
    "en": {
        "home_label": "Lumincode home", "menu_label": "Open menu", "lunar_visual_label": "Lunar learning illustration", "lesson_path_label": "PYTHON PATH / LESSON",
        "copy_failed": "Could not copy", "no_code": "No code to copy",
        "lesson_flow": "YOUR LEARNING FLOW", "scroll_hint": "Keep scrolling — each idea unfolds as you go.",
        "step_explanation": "IN PLAIN WORDS", "step_result": "WHAT YOU SEE", "video_source": "CURATED VIDEO",
        "watch_youtube": "Watch on YouTube", "video_language_note": "The lesson text is in your selected language. This video is in English.",
        "flow_progress": "Lesson flow", "guided_title": "Let’s read the code together", "guided_intro": "A program is a list of instructions. Python reads them from top to bottom. Start with one line, then add meaning one piece at a time.",
        "term_print": "print()", "term_print_text": "print() is a built-in function that sends a value to the program’s output. The parentheses contain the value you want to show.",
        "term_string": "str · text", "term_string_text": "Text is a string (str). Quotes tell Python that Hello is text, not the name of a variable or command.",
        "term_variable": "variable", "term_variable_text": "A variable is a readable name for a value. The equals sign stores the value on the right under the name on the left.",
        "term_int": "int · whole number", "term_int_text": "int means integer: a whole number such as 21. int(\"21\") converts the text \"21\" into the number 21 so Python can do arithmetic with it.",
        "term_type": "type()", "term_type_text": "type(value) asks Python what kind of value it is. For age, the answer is int. __name__ shows the short type name.",
        "guided_finish": "You’ve just seen text, variables, conversion, and output work together. Next, change the name or age and follow the result.",
        "output_label": "PROGRAM OUTPUT", "input_label": "INPUT", "process_label": "PROCESS", "result_label": "OUTPUT",
    },
    "ru": {
        "home_label": "На главную Lumincode", "menu_label": "Открыть меню", "lunar_visual_label": "Лунная учебная иллюстрация", "lesson_path_label": "КУРС PYTHON / УРОК",
        "copy_failed": "Не удалось скопировать", "no_code": "Нет кода для копирования",
        "lesson_flow": "ТВОЙ ПУТЬ ПО УРОКУ", "scroll_hint": "Листай дальше — следующие идеи появятся по ходу.",
        "step_explanation": "ПРОСТЫМИ СЛОВАМИ", "step_result": "ЧТО ПОЛУЧИТСЯ", "video_source": "ПОДОБРАННОЕ ВИДЕО",
        "watch_youtube": "Смотреть на YouTube", "video_language_note": "Текст урока — на выбранном языке. Видео — на английском.",
        "flow_progress": "Ход урока", "guided_title": "Разберём код вместе", "guided_intro": "Программа — это список инструкций. Python читает их сверху вниз. Начнём с одной строки и будем добавлять смысл по частям.",
        "term_print": "print()", "term_print_text": "Встроенная функция print() отправляет значение в вывод программы. В скобках указывают, что нужно показать.",
        "term_string": "str · текст", "term_string_text": "Текст — это строка (str). Кавычки показывают Python, что Hello — текст, а не имя переменной или команды.",
        "term_variable": "переменная", "term_variable_text": "Переменная — понятное имя для значения. Знак равенства сохраняет значение справа под именем слева.",
        "term_int": "int · целое число", "term_int_text": "int — целое число без дробной части, например 21. int(\"21\") превращает текст \"21\" в число 21, с которым можно считать.",
        "term_type": "type()", "term_type_text": "type(value) спрашивает Python, какого типа значение. Для age ответ — int. __name__ показывает короткое имя типа.",
        "guided_finish": "Ты увидел, как текст, переменные, преобразование типов и вывод работают вместе. Теперь измени имя или возраст и проследи результат.",
        "output_label": "ВЫВОД ПРОГРАММЫ", "input_label": "ВВОД", "process_label": "ОБРАБОТКА", "result_label": "РЕЗУЛЬТАТ",
    },
    "fr": {
        "home_label": "Accueil Lumincode", "menu_label": "Ouvrir le menu", "lunar_visual_label": "Illustration lunaire d’apprentissage", "lesson_path_label": "PARCOURS PYTHON / LEÇON",
        "copy_failed": "Copie impossible", "no_code": "Aucun code à copier",
        "lesson_flow": "VOTRE PARCOURS DANS LA LEÇON", "scroll_hint": "Continuez à faire défiler : chaque idée se dévoile au fil du parcours.",
        "step_explanation": "EN TERMES SIMPLES", "step_result": "RÉSULTAT À L’ÉCRAN", "video_source": "VIDÉO SÉLECTIONNÉE",
        "watch_youtube": "Regarder sur YouTube", "video_language_note": "Le texte du cours est dans la langue choisie. Cette vidéo est en anglais.",
        "flow_progress": "Progression de la leçon", "guided_title": "Découvrons le code ensemble", "guided_intro": "Un programme est une liste d’instructions. Python les lit de haut en bas. Commençons par une ligne, puis ajoutons le sens petit à petit.",
        "term_print": "print()", "term_print_text": "La fonction intégrée print() envoie une valeur vers la sortie du programme. Les parenthèses contiennent la valeur à afficher.",
        "term_string": "str · texte", "term_string_text": "Un texte est une chaîne (str). Les guillemets indiquent à Python que Hello est du texte, pas un nom de variable ou de commande.",
        "term_variable": "variable", "term_variable_text": "Une variable est un nom lisible associé à une valeur. Le signe égal enregistre la valeur de droite sous le nom de gauche.",
        "term_int": "int · entier", "term_int_text": "int signifie entier : un nombre sans décimales, comme 21. int(\"21\") convertit le texte \"21\" en nombre pour pouvoir calculer.",
        "term_type": "type()", "term_type_text": "type(value) demande à Python la catégorie de la valeur. Pour age, la réponse est int. __name__ affiche le nom court du type.",
        "guided_finish": "Vous venez de voir le texte, les variables, la conversion et l’affichage fonctionner ensemble. Modifiez maintenant le nom ou l’âge et observez le résultat.",
        "output_label": "SORTIE DU PROGRAMME", "input_label": "ENTRÉE", "process_label": "TRAITEMENT", "result_label": "SORTIE",
    },
    "es": {
        "home_label": "Inicio de Lumincode", "menu_label": "Abrir menú", "lunar_visual_label": "Ilustración lunar de aprendizaje", "lesson_path_label": "RUTA PYTHON / LECCIÓN",
        "copy_failed": "No se pudo copiar", "no_code": "No hay código para copiar",
        "lesson_flow": "TU RECORRIDO POR LA LECCIÓN", "scroll_hint": "Sigue bajando: cada idea aparece a medida que avanzas.",
        "step_explanation": "EN PALABRAS SENCILLAS", "step_result": "LO QUE VERÁS", "video_source": "VÍDEO RECOMENDADO",
        "watch_youtube": "Ver en YouTube", "video_language_note": "El texto de la lección está en el idioma elegido. Este vídeo está en inglés.",
        "flow_progress": "Progreso de la lección", "guided_title": "Leamos el código juntos", "guided_intro": "Un programa es una lista de instrucciones. Python las lee de arriba abajo. Empecemos con una línea y añadamos significado poco a poco.",
        "term_print": "print()", "term_print_text": "La función incorporada print() envía un valor a la salida del programa. Los paréntesis contienen lo que quieres mostrar.",
        "term_string": "str · texto", "term_string_text": "Un texto es una cadena (str). Las comillas indican a Python que Hello es texto, no el nombre de una variable o instrucción.",
        "term_variable": "variable", "term_variable_text": "Una variable es un nombre legible asociado a un valor. El signo igual guarda el valor de la derecha con el nombre de la izquierda.",
        "term_int": "int · entero", "term_int_text": "int significa entero: un número sin decimales, como 21. int(\"21\") convierte el texto \"21\" en el número 21 para poder calcular.",
        "term_type": "type()", "term_type_text": "type(value) pregunta a Python qué tipo de valor es. Para age, la respuesta es int. __name__ muestra el nombre corto del tipo.",
        "guided_finish": "Ya has visto cómo se combinan texto, variables, conversión y salida. Cambia ahora el nombre o la edad y observa el resultado.",
        "output_label": "SALIDA DEL PROGRAMA", "input_label": "ENTRADA", "process_label": "PROCESO", "result_label": "SALIDA",
    },
    "hy": {
        "home_label": "Lumincode-ի գլխավոր էջ", "menu_label": "Բացել ցանկը", "lunar_visual_label": "Լուսնային ուսուցման պատկերազարդում", "lesson_path_label": "PYTHON ՈՒՂԻ / ԴԱՍ",
        "copy_failed": "Չհաջողվեց պատճենել", "no_code": "Պատճենելու կոդ չկա",
        "lesson_flow": "ՔՈ ՈՒՂԻՆ ԴԱՍԻ ՄԵՋ", "scroll_hint": "Շարունակիր իջնել․ հաջորդ գաղափարները կբացվեն հերթով։",
        "step_explanation": "ՊԱՐԶ ԲԱՌԵՐՈՎ", "step_result": "ԱՅՍ ԿՏԵՍՆԵՍ", "video_source": "ԸՆՏՐՎԱԾ ՏԵՍԱՆՅՈՒԹ",
        "watch_youtube": "Դիտել YouTube-ում", "video_language_note": "Դասի տեքստը քո ընտրած լեզվով է։ Այս տեսանյութը անգլերեն է։",
        "flow_progress": "Դասի ընթացքը", "guided_title": "Եկ միասին կարդանք կոդը", "guided_intro": "Ծրագիրը հրահանգների ցուցակ է։ Python-ը դրանք կարդում է վերևից ներքև։ Սկսենք մեկ տողից և քայլ առ քայլ հասկանանք դրա մասերը։",
        "term_print": "print()", "term_print_text": "Ներկառուցված print() ֆունկցիան արժեքը գրում է ծրագրի ելքում։ Փակագծերի մեջ նշում ենք, թե ինչն է պետք ցուցադրել։",
        "term_string": "str · տեքստ", "term_string_text": "Տեքստը տող է (str)։ Չակերտները Python-ին ասում են, որ Hello-ն տեքստ է, ոչ թե փոփոխականի կամ հրահանգի անուն։",
        "term_variable": "փոփոխական", "term_variable_text": "Փոփոխականը արժեքի համար ընթեռնելի անուն է։ Հավասարության նշանը աջ կողմի արժեքը պահում է ձախ կողմի անվան տակ։",
        "term_int": "int · ամբողջ թիվ", "term_int_text": "int-ը ամբողջ թիվ է՝ առանց կոտորակային մասի, օրինակ՝ 21։ int(\"21\")-ը \"21\" տեքստը դարձնում է 21 թիվ, որպեսզի կարողանաս հաշվել։",
        "term_type": "type()", "term_type_text": "type(value)-ը Python-ին հարցնում է արժեքի տեսակը։ age-ի դեպքում պատասխանը int է։ __name__-ը ցույց է տալիս տեսակի կարճ անունը։",
        "guided_finish": "Դու տեսար, թե ինչպես են տեքստը, փոփոխականները, տեսակի փոխարկումն ու ելքը միասին աշխատում։ Փոխիր անունը կամ տարիքը և հետևիր արդյունքին։",
        "output_label": "ԾՐԱԳՐԻ ԵԼՔԸ", "input_label": "ՄՈՒՏՔ", "process_label": "ՄՇԱԿՈՒՄ", "result_label": "ԵԼՔ",
    },
}
for _language, _strings in UI_EXTRA.items():
    UI[_language].update(_strings)
    UI[_language].update(UI_LESSON_FLOW[_language])


LESSONS = [
    {
        "slug": "first-program", "code": 'print("Hello, world!")\nname = "Mira"\nage = int("21")\nprint(name, age)\nprint(type(age).__name__)',
        "locales": {
            "en": ("Your first Python program", "Python reads instructions from top to bottom. print() puts a value in the output. Quotes mark text (str); a variable gives a value a useful name. int() turns digit-text into a whole number, and type() lets you inspect a value.", "Python evaluates the expression inside print() and writes the result to the output. int(\"21\") converts a string into an integer before it is stored in age.", "Try changing Mira to your name. Keep text in quotes, and use int(\"21\") when you need a number instead of digit-text.", "What does int(\"21\") produce?", ["The text \"21\"", "The whole number 21", "The decimal number 2.1"], 1),
            "ru": ("Первая программа на Python", "Python читает команды сверху вниз. print() выводит значение. Кавычки обозначают текст (str); переменная даёт значению понятное имя. int() превращает цифры-текст в целое число, а type() показывает тип значения.", "Python вычисляет выражение внутри print() и отправляет результат в вывод. int(\"21\") преобразует строку в целое число перед сохранением в age.", "Попробуй заменить Mira своим именем. Текст оставляй в кавычках; используй int(\"21\"), когда нужны числа, а не текст из цифр.", "Что возвращает int(\"21\")?", ["Текст \"21\"", "Целое число 21", "Десятичное число 2,1"], 1),
            "fr": ("Votre premier programme Python", "Python lit les instructions de haut en bas. print() affiche une valeur. Les guillemets marquent le texte (str) ; une variable donne un nom utile à une valeur. int() transforme du texte composé de chiffres en entier et type() inspecte une valeur.", "Python calcule l’expression dans print() puis écrit le résultat dans la sortie. int(\"21\") convertit une chaîne en entier avant de la stocker dans age.", "Remplacez Mira par votre prénom. Gardez le texte entre guillemets et utilisez int(\"21\") pour obtenir un nombre plutôt qu’un texte composé de chiffres.", "Que produit int(\"21\") ?", ["Le texte \"21\"", "L’entier 21", "Le nombre décimal 2,1"], 1),
            "es": ("Tu primer programa en Python", "Python lee las instrucciones de arriba abajo. print() muestra un valor. Las comillas marcan texto (str); una variable da un nombre útil a un valor. int() convierte texto con dígitos en un número entero y type() permite consultar el tipo.", "Python evalúa la expresión de print() y escribe el resultado en la salida. int(\"21\") convierte una cadena en un entero antes de guardarlo en age.", "Cambia Mira por tu nombre. Mantén el texto entre comillas y usa int(\"21\") para obtener un número en vez de texto formado por dígitos.", "¿Qué produce int(\"21\")?", ["El texto \"21\"", "El número entero 21", "El número decimal 2,1"], 1),
            "hy": ("Քո առաջին Python ծրագիրը", "Python-ը հրահանգները կարդում է վերևից ներքև։ print()-ը արժեքը գրում է ելքում։ Չակերտները նշանակում են տեքստ (str), իսկ փոփոխականը արժեքին տալիս է հասկանալի անուն։ int()-ը թվանշաններից կազմված տեքստը դարձնում է ամբողջ թիվ, իսկ type()-ը ցույց է տալիս արժեքի տեսակը։", "Python-ը հաշվում է print()-ի ներսում եղած արտահայտությունը և արդյունքը գրում ելքում։ int(\"21\")-ը տողը վերածում է ամբողջ թվի՝ age-ում պահելուց առաջ։", "Mira-ի փոխարեն գրիր քո անունը։ Տեքստը պահիր չակերտների մեջ, իսկ int(\"21\")-ն օգտագործիր, երբ թվանշանների տեքստի փոխարեն թիվ է պետք։", "Ի՞նչ է վերադարձնում int(\"21\")-ը։", ["\"21\" տեքստը", "21 ամբողջ թիվը", "2.1 տասնորդական թիվը"], 1),
        },
    },
    {
        "slug": "values-and-types", "code": 'age = 21\nname = "Mira"\nis_learning = True\nprint(type(age))',
        "locales": {
            "en": ("Variables and data types", "Python infers a value's type. Common types include int, float, str, and bool. Names should describe the data; reassignment changes the value a name refers to.", "A variable name points to an object. Conversions such as int('4') create a value of another type.", "Use type(value) to inspect a value. Convert input before doing arithmetic because input() returns text.", "What is the type of True?", ["str", "bool", "int"], 1),
            "ru": ("Переменные и типы данных", "Python определяет тип значения автоматически. Частые типы: int, float, str и bool. Выбирай понятные имена; повторное присваивание меняет значение переменной.", "Имя переменной ссылается на объект. Преобразование вроде int('4') создаёт значение другого типа.", "Проверить тип помогает type(value). Преобразуй ввод перед вычислениями: input() возвращает текст.", "Какой тип у значения True?", ["str", "bool", "int"], 1),
            "fr": ("Variables et types de données", "Python déduit le type d’une valeur. Les types courants sont int, float, str et bool. Choisissez des noms clairs ; une nouvelle affectation remplace la valeur référencée.", "Un nom de variable référence un objet. int('4') convertit, par exemple, le texte en entier.", "type(value) révèle le type. Convertissez input() avant un calcul, car cette fonction renvoie du texte.", "Quel est le type de True ?", ["str", "bool", "int"], 1),
            "es": ("Variables y tipos de datos", "Python deduce el tipo de cada valor. Los tipos habituales son int, float, str y bool. Usa nombres claros; una nueva asignación cambia el valor asociado al nombre.", "Una variable referencia un objeto. int('4'), por ejemplo, convierte texto en un entero.", "type(value) muestra el tipo. Convierte el resultado de input() antes de calcular, porque devuelve texto.", "¿Qué tipo tiene True?", ["str", "bool", "int"], 1),
            "hy": ("Փոփոխականներ և տվյալների տեսակներ", "Python-ը որոշում է արժեքի տեսակը։ Հիմնական տեսակներն են int, float, str և bool։ Ընտրիր հստակ անուններ․ նոր վերագրումը փոխում է փոփոխականին կապված արժեքը։", "Փոփոխականի անունը հղում է օբյեկտին։ int('4')-ը, օրինակ, տեքստը վերածում է ամբողջ թվի։", "type(value)-ը ցույց է տալիս տեսակը։ input()-ի արդյունքը փոխարկիր մինչև հաշվարկը, քանի որ այն վերադարձնում է տեքստ։", "Ի՞նչ տեսակ ունի True արժեքը։", ["str", "bool", "int"], 1),
        },
    },
    {
        "slug": "branches-and-loops", "code": 'for number in range(3):\n    if number % 2 == 0:\n        print(number, "is even")',
        "locales": {
            "en": ("Conditions and loops", "if/elif/else chooses a branch from a Boolean condition. for repeats over a sequence; while repeats while a condition is true. A loop body is indented.", "range(3) produces 0, 1, 2. The remainder operator % can test whether a number is even.", "Trace one iteration at a time. Make sure a while loop changes its condition so it can stop.", "Which values does range(3) produce?", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3"], 1),
            "ru": ("Условия и циклы", "if/elif/else выбирает ветку по логическому условию. for перебирает последовательность, а while повторяет действия, пока условие истинно. Тело цикла имеет отступ.", "range(3) создаёт значения 0, 1, 2. Оператор остатка % помогает проверить чётность.", "Проследи за каждым повтором отдельно. В цикле while меняй условие, чтобы цикл мог завершиться.", "Какие значения создаёт range(3)?", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3"], 1),
            "fr": ("Conditions et boucles", "if/elif/else choisit une branche selon une condition booléenne. for parcourt une séquence ; while répète tant que sa condition est vraie. Le corps est indenté.", "range(3) produit 0, 1, 2. L’opérateur % peut vérifier si un nombre est pair.", "Suivez chaque itération. Dans une boucle while, faites évoluer la condition pour pouvoir l’arrêter.", "Quelles valeurs produit range(3) ?", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3"], 1),
            "es": ("Condiciones y bucles", "if/elif/else elige una rama según una condición booleana. for recorre una secuencia; while repite mientras la condición sea verdadera. El cuerpo lleva sangría.", "range(3) produce 0, 1, 2. El operador % permite comprobar si un número es par.", "Sigue cada iteración. En un bucle while, cambia la condición para que pueda terminar.", "¿Qué valores produce range(3)?", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3"], 1),
            "hy": ("Պայմաններ և ցիկլեր", "if/elif/else-ը ճյուղ է ընտրում տրամաբանական պայմանից։ for-ը անցնում է հաջորդականության տարրերով, իսկ while-ը կրկնում է, քանի դեռ պայմանը ճիշտ է։ Ցիկլի մարմինը նահանջով է գրվում։", "range(3)-ը ստեղծում է 0, 1, 2 արժեքները։ % մնացորդի օպերատորը կարող է ստուգել թվի զույգ լինելը։", "Հետևիր յուրաքանչյուր կրկնությանը։ while ցիկլում փոխիր պայմանը, որպեսզի այն կարողանա ավարտվել։", "Ի՞նչ արժեքներ է ստեղծում range(3)-ը։", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3"], 1),
        },
    },
    {
        "slug": "collections", "code": 'scores = [8, 10, 9]\nprofile = {"name": "Mira", "level": 2}\nprint(profile["name"], max(scores))',
        "locales": {
            "en": ("Collections: lists, tuples, sets, dictionaries", "Lists keep an ordered, changeable sequence. Tuples are ordered and immutable. Sets hold unique values. Dictionaries map keys to values and are useful for named facts.", "Choose a structure by the operations you need: index a list, test set membership, or look up a dictionary key.", "A missing dictionary key raises KeyError. Use .get(key, default) when a value may be absent.", "What does a dictionary store?", ["Only unique values", "Key-value pairs", "An ordered immutable sequence"], 1),
            "ru": ("Коллекции: списки, кортежи, множества, словари", "Список хранит упорядоченную изменяемую последовательность. Кортеж упорядочен, но неизменяем. Множество содержит уникальные значения. Словарь связывает ключи со значениями.", "Выбирай структуру по нужным операциям: индексируй список, проверяй наличие в множестве или ищи по ключу словаря.", "Отсутствующий ключ вызывает KeyError. Используй .get(key, default), если значения может не быть.", "Что хранит словарь?", ["Только уникальные значения", "Пары «ключ — значение»", "Упорядоченную неизменяемую последовательность"], 1),
            "fr": ("Collections : listes, tuples, ensembles et dictionnaires", "Une liste conserve une séquence ordonnée et modifiable. Un tuple est ordonné mais immuable. Un ensemble contient des valeurs uniques. Un dictionnaire associe des clés à des valeurs.", "Choisissez la structure selon l’opération : indexer une liste, tester l’appartenance à un ensemble ou chercher une clé.", "Une clé absente déclenche KeyError. Utilisez .get(key, default) si la valeur peut manquer.", "Que stocke un dictionnaire ?", ["Des valeurs uniques seulement", "Des paires clé-valeur", "Une séquence ordonnée immuable"], 1),
            "es": ("Colecciones: listas, tuplas, conjuntos y diccionarios", "Una lista guarda una secuencia ordenada y modificable. Una tupla es ordenada e inmutable. Un conjunto contiene valores únicos. Un diccionario relaciona claves con valores.", "Elige la estructura según la operación: indexar una lista, comprobar un conjunto o buscar una clave.", "Una clave inexistente genera KeyError. Usa .get(key, default) cuando el valor puede faltar.", "¿Qué guarda un diccionario?", ["Solo valores únicos", "Pares de clave y valor", "Una secuencia ordenada e inmutable"], 1),
            "hy": ("Հավաքածուներ․ ցուցակներ, tuple, set և բառարաններ", "Ցուցակը պահում է հերթականությամբ դասավորված և փոփոխվող արժեքներ։ tuple-ը հերթական է, բայց անփոփոխ։ set-ը պահում է եզակի արժեքներ։ Բառարանը բանալիները կապում է արժեքների հետ։", "Կառուցվածքն ընտրիր ըստ գործողության․ ցուցակը ինդեքսավորիր, set-ում անդամակցությունը ստուգիր կամ բառարանում բանալիով որոնիր։", "Բացակայող բանալին առաջացնում է KeyError։ Օգտագործիր .get(key, default), եթե արժեքը կարող է բացակայել։", "Ի՞նչ է պահում բառարանը։", ["Միայն եզակի արժեքներ", "Բանալի-արժեք զույգեր", "Հերթական և անփոփոխ հաջորդականություն"], 1),
        },
    },
    {
        "slug": "functions", "code": 'def average(values: list[float]) -> float:\n    return sum(values) / len(values)\n\nprint(average([8, 10, 9]))',
        "locales": {
            "en": ("Functions and reusable code", "A function groups a task behind a name. Parameters receive inputs; return sends a result back to the caller. Type hints document expected values but do not replace runtime checks.", "Calling a function transfers control to its body, then returns to the line after the call.", "Prefer small functions with one clear purpose. Avoid mutable default arguments such as items=[]; create the list inside instead.", "What does return do?", ["Displays text", "Sends a result back to the caller", "Repeats a function"], 1),
            "ru": ("Функции и повторное использование кода", "Функция объединяет задачу под одним именем. Параметры принимают входные данные, а return возвращает результат вызывающему коду. Аннотации типов документируют ожидания, но не заменяют проверки.", "При вызове выполнение переходит в тело функции, затем возвращается к строке после вызова.", "Пиши небольшие функции с одной задачей. Не используй изменяемые значения по умолчанию вроде items=[] — создавай список внутри.", "Что делает return?", ["Выводит текст", "Возвращает результат вызывающему коду", "Повторяет функцию"], 1),
            "fr": ("Fonctions et code réutilisable", "Une fonction regroupe une tâche sous un nom. Les paramètres reçoivent les entrées ; return renvoie un résultat à l’appelant. Les annotations décrivent les types attendus sans remplacer les vérifications.", "L’appel entre dans le corps de la fonction puis revient à la ligne qui suit l’appel.", "Préférez de petites fonctions à but unique. Évitez les valeurs par défaut mutables comme items=[] ; créez la liste dans la fonction.", "Que fait return ?", ["Affiche du texte", "Renvoie un résultat à l’appelant", "Répète une fonction"], 1),
            "es": ("Funciones y código reutilizable", "Una función agrupa una tarea bajo un nombre. Los parámetros reciben entradas y return devuelve un resultado a quien la llamó. Las anotaciones documentan tipos, pero no sustituyen las comprobaciones.", "Al llamar una función, se ejecuta su cuerpo y luego se vuelve a la línea siguiente a la llamada.", "Prefiere funciones pequeñas con un propósito claro. Evita valores mutables por defecto como items=[]; crea la lista dentro.", "¿Qué hace return?", ["Muestra texto", "Devuelve un resultado a quien llamó", "Repite una función"], 1),
            "hy": ("Ֆունկցիաներ և կրկնակի օգտագործվող կոդ", "Ֆունկցիան միավորում է առաջադրանքը անվան տակ։ Պարամետրերը ստանում են մուտքային արժեքները, իսկ return-ը արդյունքը վերադարձնում է կանչող կոդին։ Տիպերի նշումները նկարագրում են սպասվող արժեքները, բայց չեն փոխարինում ստուգումներին։", "Կանչից հետո կառավարումը մտնում է ֆունկցիայի մարմին, ապա վերադառնում է կանչից հետո տողին։", "Գրիր փոքր ֆունկցիաներ՝ մեկ հստակ նպատակով։ Մի օգտագործիր փոփոխվող լռելյայն արժեքներ, օրինակ՝ items=[]․ ցուցակը ստեղծիր ֆունկցիայի ներսում։", "Ի՞նչ է անում return-ը։", ["Ցուցադրում է տեքստ", "Արդյունքը վերադարձնում է կանչող կոդին", "Կրկնում է ֆունկցիան"], 1),
        },
    },
    {
        "slug": "modules-errors-files", "code": 'from pathlib import Path\n\ntry:\n    Path("notes.txt").write_text("Keep learning!")\nexcept OSError as error:\n    print("Could not save:", error)',
        "locales": {
            "en": ("Modules, errors, and files", "Modules organize code into files you can import. Exceptions represent errors; try/except lets you handle expected failures. pathlib offers clear, cross-platform file paths.", "Use a narrow exception handler around the operation that can fail. A context manager with open() closes files even when an error occurs.", "Catch only errors you can respond to. Never hide every failure with a bare except.", "Why handle OSError around a file write?", ["A file write can fail due to the system or permissions", "It changes a string into a number", "It makes Python run faster"], 0),
            "ru": ("Модули, ошибки и файлы", "Модули организуют код в файлах, которые можно импортировать. Исключения обозначают ошибки; try/except помогает обработать ожидаемый сбой. pathlib упрощает работу с путями.", "Обрабатывай исключение рядом с операцией, которая может завершиться сбоем. Контекстный менеджер с open() закрывает файл даже при ошибке.", "Перехватывай только те ошибки, на которые можешь отреагировать. Не скрывай всё через пустой except.", "Зачем обрабатывать OSError при записи файла?", ["Запись может не получиться из-за системы или прав", "Она превращает строку в число", "Она ускоряет Python"], 0),
            "fr": ("Modules, erreurs et fichiers", "Les modules organisent le code dans des fichiers importables. Les exceptions représentent les erreurs ; try/except permet de gérer les échecs prévus. pathlib simplifie les chemins multiplateformes.", "Placez un gestionnaire précis autour de l’opération risquée. Un gestionnaire de contexte avec open() ferme le fichier même en cas d’erreur.", "Ne gérez que les erreurs auxquelles vous pouvez répondre. Ne masquez pas tout avec un except vide.", "Pourquoi gérer OSError lors d’une écriture de fichier ?", ["L’écriture peut échouer à cause du système ou des droits", "Cela convertit du texte en nombre", "Cela accélère Python"], 0),
            "es": ("Módulos, errores y archivos", "Los módulos organizan el código en archivos que se pueden importar. Las excepciones representan errores; try/except permite gestionar fallos previstos. pathlib simplifica las rutas multiplataforma.", "Coloca un manejador concreto alrededor de la operación que puede fallar. Un gestor de contexto con open() cierra el archivo aunque ocurra un error.", "Captura solo los errores que puedas resolver. No ocultes todos los fallos con un except vacío.", "¿Por qué gestionar OSError al escribir un archivo?", ["La escritura puede fallar por el sistema o los permisos", "Convierte texto en número", "Hace que Python sea más rápido"], 0),
            "hy": ("Մոդուլներ, սխալներ և ֆայլեր", "Մոդուլները կոդը կազմակերպում են ներմուծվող ֆայլերում։ Բացառությունները ներկայացնում են սխալները, իսկ try/except-ը մշակում է սպասվող խափանումները։ pathlib-ը պարզեցնում է ֆայլերի ուղիները։", "Նեղ բացառության մշակում տեղադրիր այն գործողության շուրջ, որը կարող է ձախողվել։ open()-ի հետ համատեքստային կառավարիչը փակում է ֆայլը նույնիսկ սխալի դեպքում։", "Մշակիր միայն այն սխալները, որոնց կարող ես արձագանքել։ Մի թաքցրու բոլոր խափանումները դատարկ except-ով։", "Ինչո՞ւ OSError մշակել ֆայլ գրելու ժամանակ։", ["Գրառումը կարող է ձախողվել համակարգի կամ թույլտվության պատճառով", "Այն տեքստը դարձնում է թիվ", "Այն արագացնում է Python-ը"], 0),
        },
    },
    {
        "slug": "object-oriented-python", "code": 'class Counter:\n    def __init__(self, start: int = 0):\n        self.value = start\n\n    def increment(self) -> None:\n        self.value += 1\n\ncount = Counter()\ncount.increment()',
        "locales": {
            "en": ("Object-oriented Python", "A class describes data and behavior for its instances. __init__ initializes a new object. Methods receive the current instance as self — like this in JavaScript, Java, or C#, but written explicitly in Python. Prefer composition when one object uses another without inheriting its identity.", "Counter() creates an instance, then increment() changes the state belonging to that instance.", "Keep object state valid through small methods. Inheritance is useful for a true subtype relationship, not just code reuse.", "What is self inside an instance method?", ["The current object", "The parent class", "A global variable"], 0),
            "ru": ("Объектно-ориентированный Python", "Класс описывает данные и поведение своих экземпляров. __init__ настраивает новый объект. Методы получают текущий экземпляр как self — по смыслу это похоже на this в JavaScript, Java или C#, но в Python параметр указывают явно. Композиция подходит, когда объект использует другой, но не является его разновидностью.", "Counter() создаёт экземпляр, а increment() меняет состояние именно этого объекта.", "Поддерживай корректное состояние объекта с помощью небольших методов. Наследование используй для настоящего отношения «является», а не только ради повторного кода.", "Что означает self в методе экземпляра?", ["Текущий объект", "Родительский класс", "Глобальную переменную"], 0),
            "fr": ("Programmation orientée objet en Python", "Une classe décrit les données et le comportement de ses instances. __init__ initialise un nouvel objet. Les méthodes reçoivent l’instance courante sous le nom self — l’idée ressemble à this en JavaScript, Java ou C#, mais le paramètre est explicite en Python. La composition convient lorsqu’un objet utilise un autre sans en être un sous-type.", "Counter() crée une instance, puis increment() modifie l’état de cette instance.", "Gardez l’état valide avec de petites méthodes. Réservez l’héritage à une vraie relation de sous-type.", "Que représente self dans une méthode d’instance ?", ["L’objet courant", "La classe parente", "Une variable globale"], 0),
            "es": ("Programación orientada a objetos en Python", "Una clase describe los datos y el comportamiento de sus instancias. __init__ inicializa un objeto. Los métodos reciben la instancia actual como self, parecido a this en JavaScript, Java o C#, pero en Python el parámetro se escribe explícitamente. La composición sirve cuando un objeto usa otro sin ser una versión de ese tipo.", "Counter() crea una instancia y increment() cambia el estado de esa instancia.", "Mantén válido el estado con métodos pequeños. Usa herencia cuando exista una relación real de subtipo.", "¿Qué representa self en un método de instancia?", ["El objeto actual", "La clase padre", "Una variable global"], 0),
            "hy": ("Օբյեկտակողմնորոշված Python", "Դասը նկարագրում է իր օրինակների տվյալներն ու վարքը։ __init__-ը սկզբնավորում է նոր օբյեկտը։ Մեթոդները ընթացիկ օրինակը ստանում են self անունով․ իմաստով այն նման է JavaScript-ի, Java-ի կամ C#-ի this-ին, բայց Python-ում պարամետրը բացահայտ գրվում է։ Կոմպոզիցիան օգտակար է, երբ օբյեկտը օգտագործում է մեկ ուրիշը՝ առանց դրա ենթատեսակ լինելու։", "Counter()-ը ստեղծում է օրինակ, իսկ increment()-ը փոխում է հենց այդ օրինակի վիճակը։", "Պահպանիր օբյեկտի վիճակը վավեր փոքր մեթոդներով։ Ժառանգությունն օգտագործիր իրական ենթատեսակի կապի դեպքում։", "Ի՞նչ է նշանակում self-ը օրինակի մեթոդում։", ["Ընթացիկ օբյեկտը", "Ծնող դասը", "Գլոբալ փոփոխականը"], 0),
        },
    },
    {
        "slug": "algorithms-complexity", "code": 'def binary_search(values: list[int], target: int) -> int | None:\n    low, high = 0, len(values) - 1\n    while low <= high:\n        middle = (low + high) // 2\n        if values[middle] == target:\n            return middle\n        if values[middle] < target:\n            low = middle + 1\n        else:\n            high = middle - 1\n    return None',
        "locales": {
            "en": ("Algorithms, recursion, and Big O", "An algorithm is a finite procedure for a problem. Big O describes how work grows with input size. Binary search halves a sorted search range each step, so its time grows logarithmically.", "The sorted-input requirement is essential: after comparing the middle value, ordering tells us which half can be discarded.", "Write down preconditions and edge cases. For binary search, test an empty list, first and last elements, and a missing target.", "What is the time complexity of binary search on a sorted list?", ["O(n)", "O(log n)", "O(n²)"], 1),
            "ru": ("Алгоритмы, рекурсия и Big O", "Алгоритм — конечная последовательность действий для решения задачи. Big O описывает рост объёма работы с размером входных данных. Бинарный поиск на каждом шаге делит отсортированный диапазон пополам.", "Требование сортировки обязательно: сравнение со средним значением показывает, какую половину можно отбросить.", "Запиши предусловия и граничные случаи. Проверь пустой список, крайние элементы и отсутствующую цель.", "Какова сложность бинарного поиска в отсортированном списке?", ["O(n)", "O(log n)", "O(n²)"], 1),
            "fr": ("Algorithmes, récursion et Big O", "Un algorithme est une procédure finie pour résoudre un problème. Big O décrit la croissance du travail selon la taille de l’entrée. La recherche binaire divise par deux une plage triée à chaque étape.", "Le tri préalable est essentiel : la comparaison avec la valeur médiane indique quelle moitié éliminer.", "Notez les préconditions et les cas limites. Testez une liste vide, les extrémités et une valeur absente.", "Quelle est la complexité d’une recherche binaire dans une liste triée ?", ["O(n)", "O(log n)", "O(n²)"], 1),
            "es": ("Algoritmos, recursión y Big O", "Un algoritmo es un procedimiento finito para resolver un problema. Big O describe cómo crece el trabajo con el tamaño de entrada. La búsqueda binaria divide por la mitad un rango ordenado en cada paso.", "El requisito de orden es esencial: comparar el valor central indica qué mitad se puede descartar.", "Anota las precondiciones y los casos límite. Prueba una lista vacía, los extremos y un objetivo ausente.", "¿Cuál es la complejidad de la búsqueda binaria en una lista ordenada?", ["O(n)", "O(log n)", "O(n²)"], 1),
            "hy": ("Ալգորիթմներ, ռեկուրսիա և Big O", "Ալգորիթմը խնդրի լուծման վերջավոր քայլաշար է։ Big O-ն նկարագրում է աշխատանքի աճը մուտքի չափի հետ։ Երկուական որոնումը յուրաքանչյուր քայլում կիսում է դասավորված միջակայքը։", "Դասավորված լինելու պայմանը պարտադիր է․ միջին արժեքի համեմատությունը ցույց է տալիս, թե որ կեսը կարելի է բացառել։", "Գրիր նախապայմաններն ու սահմանային դեպքերը։ Ստուգիր դատարկ ցուցակ, առաջին և վերջին տարրերը, ինչպես նաև բացակայող արժեք։", "Որքա՞ն է երկուական որոնման բարդությունը դասավորված ցուցակում։", ["O(n)", "O(log n)", "O(n²)"], 1),
        },
    },
    {
        "slug": "iterators-generators", "code": 'def countdown(start: int):\n    while start > 0:\n        yield start\n        start -= 1\n\nprint(list(countdown(3)))',
        "locales": {
            "en": ("Iterators, generators, and decorators", "An iterator yields values one at a time. A generator function uses yield and pauses between values, which can save memory for large sequences. Decorators wrap a function to add reusable behavior.", "Calling a generator returns an iterator; each next() resumes it until the next yield or completion.", "Use a generator when you can process items as they arrive. Do not turn a huge stream into a list unless you need all values at once.", "What does yield do in a generator?", ["Returns one value and pauses execution", "Ends the whole program", "Creates a class"], 0),
            "ru": ("Итераторы, генераторы и декораторы", "Итератор выдаёт значения по одному. Функция-генератор использует yield и приостанавливается между значениями, экономя память на больших последовательностях. Декоратор оборачивает функцию и добавляет повторно используемое поведение.", "Вызов генератора возвращает итератор; next() продолжает выполнение до следующего yield или завершения.", "Выбирай генератор, когда обрабатываешь значения по мере поступления. Не превращай большой поток в список без необходимости.", "Что делает yield в генераторе?", ["Возвращает значение и приостанавливает выполнение", "Завершает всю программу", "Создаёт класс"], 0),
            "fr": ("Itérateurs, générateurs et décorateurs", "Un itérateur produit les valeurs une par une. Une fonction génératrice utilise yield et se met en pause entre les valeurs, ce qui économise la mémoire. Un décorateur enveloppe une fonction pour ajouter un comportement réutilisable.", "L’appel d’un générateur renvoie un itérateur ; next() reprend jusqu’au prochain yield ou à la fin.", "Utilisez un générateur pour traiter les éléments au fil de l’eau. Évitez de convertir un grand flux en liste sans nécessité.", "Que fait yield dans un générateur ?", ["Renvoie une valeur puis suspend l’exécution", "Arrête tout le programme", "Crée une classe"], 0),
            "es": ("Iteradores, generadores y decoradores", "Un iterador entrega valores de uno en uno. Una función generadora usa yield y se pausa entre valores, lo que ahorra memoria. Un decorador envuelve una función para añadir comportamiento reutilizable.", "Al llamar a un generador se obtiene un iterador; next() lo reanuda hasta el siguiente yield o hasta terminar.", "Usa generadores para procesar elementos a medida que llegan. No conviertas un flujo enorme en lista si no hace falta.", "¿Qué hace yield en un generador?", ["Devuelve un valor y pausa la ejecución", "Termina todo el programa", "Crea una clase"], 0),
            "hy": ("Իտերատորներ, գեներատորներ և դեկորատորներ", "Իտերատորը արժեքները տրամադրում է մեկ առ մեկ։ Գեներատոր ֆունկցիան օգտագործում է yield-ը և դադար է առնում արժեքների միջև՝ մեծ հաջորդականությունների համար խնայելով հիշողությունը։ Դեկորատորը ֆունկցիան փաթեթավորում է կրկնակի օգտագործվող վարք ավելացնելու համար։", "Գեներատորի կանչը վերադարձնում է իտերատոր․ next()-ը շարունակում է մինչև հաջորդ yield-ը կամ ավարտը։", "Գեներատոր օգտագործիր, երբ տարրերը մշակում ես ստանալուն պես։ Մի փոխարկիր մեծ հոսքը ցուցակի, եթե բոլոր արժեքները միաժամանակ պետք չեն։", "Ի՞նչ է անում yield-ը գեներատորում։", ["Վերադարձնում է արժեք և դադարեցնում կատարումը", "Ավարտում է ամբողջ ծրագիրը", "Ստեղծում է դաս"], 0),
        },
    },
    {
        "slug": "testing-async", "code": 'async def fetch_label(fetch):\n    response = await fetch("/course")\n    return response["label"]\n\n# A test can assert: fetch_label(fake_fetch) == "Python"',
        "locales": {
            "en": ("Testing, async, and reliable software", "A unit test checks one behavior with known inputs and expected outputs. assert makes a mismatch visible. Async code uses async/await for cooperative I/O; it is useful when waiting on many network or file operations.", "A test calls code and compares its result. await pauses the coroutine until an awaited operation is ready without blocking the whole event loop.", "Keep tests deterministic: replace network services with small fakes. Use async only when the work actually waits on I/O.", "What should a focused unit test verify?", ["One behavior with known inputs and expected output", "The entire internet connection", "The color of the editor"], 0),
            "ru": ("Тестирование, async и надёжный код", "Модульный тест проверяет одно поведение на известных входных данных и ожидаемом результате. assert показывает несоответствие. async/await полезен для совместного ожидания множества сетевых или файловых операций.", "Тест вызывает код и сравнивает результат. await приостанавливает корутину до готовности операции, не блокируя весь цикл событий.", "Делай тесты предсказуемыми: подменяй сетевые сервисы простыми заглушками. Используй async, когда действительно ждёшь I/O.", "Что проверяет хороший модульный тест?", ["Одно поведение на известных данных и ожидаемый результат", "Всё подключение к интернету", "Цвет редактора"], 0),
            "fr": ("Tests, async et logiciels fiables", "Un test unitaire vérifie un comportement avec des entrées connues et un résultat attendu. assert rend les écarts visibles. async/await sert aux attentes d’E/S coopératives, par exemple pour plusieurs opérations réseau.", "Le test appelle le code et compare son résultat. await suspend la coroutine jusqu’à la fin de l’opération sans bloquer toute la boucle.", "Gardez des tests déterministes en remplaçant le réseau par des objets factices. N’utilisez async que pour des attentes d’E/S.", "Que doit vérifier un test unitaire ciblé ?", ["Un comportement avec des entrées et un résultat attendus", "Toute la connexion Internet", "La couleur de l’éditeur"], 0),
            "es": ("Pruebas, async y software fiable", "Una prueba unitaria verifica un comportamiento con entradas conocidas y un resultado esperado. assert hace visibles las diferencias. async/await sirve para esperar operaciones de entrada y salida sin bloquear el bucle completo.", "La prueba llama al código y compara el resultado. await pausa la corrutina hasta que termina una operación, sin bloquear todo el ciclo de eventos.", "Mantén las pruebas deterministas sustituyendo la red por objetos de prueba. Usa async cuando realmente esperes operaciones de entrada y salida.", "¿Qué debe comprobar una prueba unitaria concreta?", ["Un comportamiento con datos y resultado esperados", "Toda la conexión a internet", "El color del editor"], 0),
            "hy": ("Թեստավորում, async և հուսալի ծրագրեր", "Միավորային թեստը ստուգում է մեկ վարք՝ հայտնի մուտքերով և սպասվող ելքով։ assert-ը ցույց է տալիս անհամապատասխանությունը։ async/await-ը հարմար է բազմաթիվ ցանցային կամ ֆայլային I/O գործողությունների համատեղ սպասման համար։", "Թեստը կանչում է կոդը և համեմատում արդյունքը։ await-ը կասեցնում է կոռուտինը մինչև գործողության պատրաստ լինելը՝ առանց ամբողջ իրադարձությունների ցիկլը արգելափակելու։", "Թեստերը պահիր կանխատեսելի․ ցանցային ծառայությունները փոխարինիր պարզ կեղծ օբյեկտներով։ async օգտագործիր, երբ իսկապես սպասում ես I/O գործողությունների։", "Ի՞նչ պետք է ստուգի նպատակային միավորային թեստը։", ["Մեկ վարք՝ հայտնի մուտքով և սպասվող արդյունքով", "Ամբողջ ինտերնետ կապը", "Խմբագրիչի գույնը"], 0),
        },
    },
]

VIDEO_LIBRARY = {
    "first-program": {"id": "JP7ITIXGpHk", "start": 0, "title": "Functions, variables & types", "source": "CS50P · Harvard OpenCourseWare"},
    "values-and-types": {"id": "JP7ITIXGpHk", "start": 0, "title": "Variables, strings & integers", "source": "CS50P · Harvard OpenCourseWare"},
    "branches-and-loops": {"id": "-7xg8pGcP6w", "start": 24, "title": "Loops, lists & dictionaries", "source": "CS50P · Harvard OpenCourseWare"},
    "collections": {"id": "-7xg8pGcP6w", "start": 2436, "title": "Lists, dictionaries & iteration", "source": "CS50P · Harvard OpenCourseWare"},
    "functions": {"id": "JP7ITIXGpHk", "start": 1680, "title": "Functions, arguments & return values", "source": "CS50P · Harvard OpenCourseWare"},
    "modules-errors-files": {"id": "KD-Yoel6EVQ", "start": 24, "title": "File I/O and safe file handling", "source": "CS50P · Harvard OpenCourseWare"},
    "object-oriented-python": {"id": "e4fwY9ZsxPw", "start": 24, "title": "Object-oriented programming", "source": "CS50P · Harvard OpenCourseWare"},
    "algorithms-complexity": {"id": "k-BVLx3oh1g", "start": 0, "title": "Asymptotic complexity and Big O", "source": "Part IA Algorithms · University of Cambridge"},
    "iterators-generators": {"id": "6pgodt1mezg", "start": 7689, "title": "Iterators, generators & yield", "source": "CS50P · Harvard OpenCourseWare"},
    "testing-async": {"id": "tIrcxwLqzjQ", "start": 24, "title": "Unit tests with pytest", "source": "CS50P · Harvard OpenCourseWare"},
}

GUIDED_FIRST_PROGRAM = {
    "codes": [
        'print("Hello, world!")',
        '"Hello, world!"',
        'name = "Mira"',
        'age = int("21")',
        'print(type(age).__name__)',
    ],
    "terms": ["term_print", "term_string", "term_variable", "term_int", "term_type"],
    "results": ["Hello, world!", "str", 'name → "Mira"', "age → 21 · int", "int"],
}


def localized_lesson(lesson: dict, locale: str) -> dict:
    """Return a lesson with the requested language, falling back to English."""
    language = lesson["locales"].get(locale, lesson["locales"]["en"])
    title, theory, algorithm, hint, question, options, answer = language
    trace_case = TRACE_CASES[lesson["slug"]]
    quiz = {
        "question": question,
        "options": options,
        "answer": answer,
        "checks": [
            {"question": question, "options": options, "answer": answer},
            {"question": UI[locale]["trace_prompt"], "code": trace_case["code"], "options": trace_case["options"][locale], "answer": trace_case["answer"]},
        ],
    }
    result = {
        "slug": lesson["slug"],
        "title": title,
        "theory": theory,
        "algorithm": algorithm,
        "hint": hint,
        "code": lesson["code"],
        "quiz": quiz,
        "challenge": trace_case["mission"][locale],
        "challenge_code": trace_case["code"],
        "points": 100,
        "video": VIDEO_LIBRARY.get(lesson["slug"]),
    }
    if lesson["slug"] == "first-program":
        result["guided_steps"] = [
            {"code": code, "term": UI[locale][term], "explanation": UI[locale][f"{term}_text"], "result": output}
            for code, term, output in zip(
                GUIDED_FIRST_PROGRAM["codes"],
                GUIDED_FIRST_PROGRAM["terms"],
                GUIDED_FIRST_PROGRAM["results"],
            )
        ]
    return result


def lesson_by_slug(slug: str, locale: str) -> dict | None:
    for lesson in LESSONS:
        if lesson["slug"] == slug:
            return localized_lesson(lesson, locale)
    return None


def lesson_summaries(locale: str) -> list[dict]:
    return [localized_lesson(lesson, locale) for lesson in LESSONS]
